@startuml
'define deployment entities
database auth_db #PaleTurquoise
storage resources #Moccasin

'define components
component [Resource Server] as rs #Aquamarine
component [Web Server] as ws #PaleVioletRed
component [Master Key Server] as mks #LightSeaGreen
component [Client Resource Server] as crs #LightGreen

package "OpenABE Library" {
  component [ABE Client Library] as abecl #LightCoral
  import_public_params -- abecl
  decrypt -- abecl
  encrypt -- abecl
  import_user_key -- abecl
  generate_params -right- abecl
}

'define links to deployment entities
rs <-left-> resources: "stores & retrieves\nencrypted resources"
ws <-right-> auth_db: "user management"

'define interfaces for mks, rs & abecl
abac_model -- mks
enrollment -- mks
master_public_key -- mks
upload -- rs
download -- rs
stats -- rs
all_filenames -- rs
all_metadata -- rs
latest_mpk -- rs
latest_abac_model -- rs

'define use of interfaces for crs, mks & rs
mks -right-( generate_params
crs -down-( upload
crs -down-( download
crs -down-( stats
crs -down-( all_filenames
crs -down-( all_metadata
crs -down-( latest_mpk
crs -down-( decrypt
crs -down-( encrypt
crs -down-( import_user_key
crs -down-( import_public_params
rs ..( abac_model: "offline/manual update"
rs ..( master_public_key: "offline/manual update"

'define interfaces for crs & ws
obtain_file_list -left- crs
upload_file -- crs
encrypt_upload_file -- crs
encrypt_file -- crs
obtain_file -- crs
obtain_decrypt_file -- crs
decrypt_file -- crs
search_files -- ws
login -- ws
logout -- ws

'define web server interface use
ws -down-( obtain_file_list
ws -down-( obtain_file
ws -down-( latest_abac_model

@enduml
