@startuml
autonumber
actor User
control "OpenABE CLI"
entity "Resource Server"
User -> User: creates policy for resource\ne.g. "((Staff and Date > March 17, 2019) or Admin)"
User -> "OpenABE CLI": requests encryption of resource;\nprovides policy, private key & resource
"OpenABE CLI" -> "OpenABE CLI": processes encryption of resource
"OpenABE CLI" -> User: returns encrypted file
User -> "Resource Server": sends encrypted file for upload
"Resource Server" -> "Resource Server": processes incoming file and stores
"Resource Server" -> User: returns confirmation of successful upload
@enduml
