@startuml

folder "encrypted resource store" {
  storage resource_store #Moccasin
  database resource_db #LightBlue
}

node "Authentication (e.g. SSO)" {
  component [Authentication Service] as a_s #PaleVioletRed
  database auth_db #PaleTurquoise
}

package "OpenABE Library" {
  component [ABE Client Library] as abecl #LightCoral
  generate_params -up- abecl
  decrypt_encrypt -left- abecl
}

'define components
component [Resource Server] as rs #Aquamarine
component [Master Key Server] as mks #LightSeaGreen
component [Client Resource Server] as crs #LightGreen

'define links to deployment entities
rs <-> resource_db: "encrypted resources"
resource_db <-> resource_store: "manages resource storage"
a_s <-right-> auth_db: "user records"
crs <-right-> a_s: "authenticates user(s)"

'define interfaces for mks, rs & abecl
enrolment -- mks
attributes -- mks
master_public_key -- mks
upload_download -- rs
search_resources -- rs
latest_config -- rs

'define use of interfaces for crs, mks & rs
mks -( generate_params
crs -down-( upload_download
crs -down-( search_resources
crs -down-( latest_config
crs -down-( decrypt_encrypt
rs ..( attributes
rs ..( master_public_key: "offline/manual update"

'define interfaces for crs
client_upload_download -- crs
client_encrypt_decrypt -- crs
client_resource_search -- crs

@enduml
